service:
  name: giffy

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

functions:
  giffy:
    handler: index.handler
    events:
      - http:
          method: post
          path: /
